use_frameworks!

target 'LocationInfo_Example' do
  platform :ios, '10.0'
  pod 'LocationInfo', :path => '../'

  pod 'LMGeocoderUniversal', '~> 1.2'
  target 'LocationInfo_Tests' do
    inherit! :search_paths

    
  end
end
